# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' find the eigen ld file
#' @param ldm string, input ldm
#' @return list, type, LD threshold and each LD template
NULL

getLDPrefix <- function(mldm) {
    .Call(`_SBayesRC_getLDPrefix`, mldm)
}

getPseudoRand <- function(tempstr, type, m, blocks, startPos, thresh, rand) {
    .Call(`_SBayesRC_getPseudoRand`, tempstr, type, m, blocks, startPos, thresh, rand)
}

cutLDc <- function(tempstr, type, blocks, outDir, cutThresh = 0.995) {
    .Call(`_SBayesRC_cutLDc`, tempstr, type, blocks, outDir, cutThresh)
}

impGa <- function(tempstr, curBlock, type, z, typedIndex, m, cutThresh = 0.995, diag_mod = 0.1) {
    .Call(`_SBayesRC_impGa`, tempstr, curBlock, type, z, typedIndex, m, cutThresh, diag_mod)
}

sbayesr_eigen_joint_annot <- function(niter, burn, bhat, numAnno, annoStrs, mldmDir, vary, blkN, cgamma, startPi, rmSNPIndices, starth2 = 0.01, cutThresh = 1, bOrigin = FALSE, outPrefix = "", samVe = "fixVe", resam_thresh = 1.1, bOutDetail = FALSE, outFreq = 10L, initAnnoSS = 1.0, bOutBeta = FALSE) {
    .Call(`_SBayesRC_sbayesr_eigen_joint_annot`, niter, burn, bhat, numAnno, annoStrs, mldmDir, vary, blkN, cgamma, startPi, rmSNPIndices, starth2, cutThresh, bOrigin, outPrefix, samVe, resam_thresh, bOutDetail, outFreq, initAnnoSS, bOutBeta)
}

