# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cut the LD with new thresh
#' @param ldm string, input ldm
#' @param outfile string, output file
#' @param cutThresh double, cut threshold
#' @export
cutLD <- function(ldm, outfile, cutThresh = 1) {
    .Call(`_SBayesRC_cutLD`, ldm, outfile, cutThresh)
}

impGa <- function(ldm, z, typedIndex, m, cutThresh = 1, diag_mod = 0.1) {
    .Call(`_SBayesRC_impGa`, ldm, z, typedIndex, m, cutThresh, diag_mod)
}

sbayesr_eigen_joint_annot <- function(niter, burn, bhat, numAnno, annoStrs, mldmDir, vary, blkN, cgamma, startPi, starth2 = 0.01, cutThresh = 1, bOrigin = FALSE, outPrefix = "", samVe = "fixVe", resam_thresh = 1.1, bOutDetail = FALSE, outFreq = 10L, initAnnoSS = 1.0) {
    .Call(`_SBayesRC_sbayesr_eigen_joint_annot`, niter, burn, bhat, numAnno, annoStrs, mldmDir, vary, blkN, cgamma, startPi, starth2, cutThresh, bOrigin, outPrefix, samVe, resam_thresh, bOutDetail, outFreq, initAnnoSS)
}

